/**
 * Render an audit's fixes as one self-contained Markdown document.
 *
 * A single file rather than a zip on purpose: it can be read in the browser,
 * emailed to a developer, or handed to an agency without anyone unpacking
 * anything, and it keeps the change and the reason for it side by side.
 */

interface FixRow {
  findingCode: string;
  kind: string;
  status: string;
  severity: string;
  targetUrl: string;
  title: string;
  before: string | null;
  after: string | null;
  filePath: string | null;
  guidance: string;
}

interface AuditRow {
  url: string;
  score: number | null;
  pagesCrawled: number;
  platform: string | null;
  createdAt: Date;
  sitemapXml: string | null;
  robotsTxt: string | null;
}

const PLATFORM_LABEL: Record<string, string> = {
  wordpress: "WordPress",
  woocommerce: "WooCommerce",
  shopify: "Shopify",
  wix: "Wix",
  squarespace: "Squarespace",
  webflow: "Webflow",
  ghost: "Ghost",
  framer: "Framer",
  drupal: "Drupal",
  joomla: "Joomla",
  typo3: "TYPO3",
  magento: "Magento / Adobe Commerce",
  prestashop: "PrestaShop",
  shopware: "Shopware",
  bigcommerce: "BigCommerce",
  nextjs: "Next.js",
  nuxt: "Nuxt",
  gatsby: "Gatsby",
  astro: "Astro",
  hugo: "Hugo",
  jekyll: "Jekyll",
  html: "hand-written HTML",
};

const SEVERITY_ORDER: Record<string, number> = { critical: 0, warning: 1, info: 2 };

const SEVERITY_HEADING: Record<string, string> = {
  critical: "Critical, fix these first",
  warning: "Worth fixing",
  info: "Polish",
};

/** Fence code so a snippet containing backticks can't break out of its block. */
function fence(body: string, lang = ""): string {
  const longest = (body.match(/`+/g) ?? []).reduce((n, m) => Math.max(n, m.length), 0);
  const ticks = "`".repeat(Math.max(3, longest + 1));
  return `${ticks}${lang}\n${body}\n${ticks}`;
}

export function renderFixPack(audit: AuditRow, fixes: FixRow[]): string {
  const host = (() => {
    try {
      return new URL(audit.url).hostname;
    } catch {
      return audit.url;
    }
  })();
  const platform = audit.platform ? (PLATFORM_LABEL[audit.platform] ?? audit.platform) : null;

  const out: string[] = [];
  out.push(`# SEO fix pack, ${host}`);
  out.push("");
  out.push(
    [
      `Generated by GODEYE on ${audit.createdAt.toISOString().slice(0, 10)}`,
      `${audit.pagesCrawled} page${audit.pagesCrawled === 1 ? "" : "s"} crawled`,
      audit.score !== null ? `score ${audit.score}/100` : null,
      platform ? `detected platform: ${platform}` : null,
    ]
      .filter(Boolean)
      .join(" · "),
  );
  out.push("");

  const actionable = fixes.filter((f) => f.status !== "DISMISSED");
  if (actionable.length === 0) {
    out.push("No outstanding fixes, every issue found in this audit has been handled.");
    out.push("");
    return out.join("\n");
  }

  out.push("## How to use this");
  out.push("");
  out.push(
    platform
      ? `Each fix below names where it goes in ${platform}. Work down from Critical, ` +
          "the order is by how much it costs you to leave it alone."
      : "Work down from Critical, the order is by how much it costs you to leave it alone.",
  );
  out.push("");
  out.push(
    "When a fix shows both **Currently** and **Change to**, replace the first with " +
      "the second. Where a field expects plain text rather than HTML (most CMS SEO " +
      "panels do), paste only the text between the tags.",
  );
  out.push("");
  out.push(
    "Once you have made these changes, mark them applied in GODEYE. It re-crawls the " +
      "pages and confirms each one actually took effect, a fix nobody re-checked is a " +
      "claim, not a result.",
  );
  out.push("");

  const sorted = [...actionable].sort(
    (a, b) => (SEVERITY_ORDER[a.severity] ?? 3) - (SEVERITY_ORDER[b.severity] ?? 3),
  );

  let lastSeverity = "";
  let index = 0;
  for (const fix of sorted) {
    if (fix.severity !== lastSeverity) {
      lastSeverity = fix.severity;
      out.push(`## ${SEVERITY_HEADING[fix.severity] ?? fix.severity}`);
      out.push("");
    }
    index += 1;
    out.push(`### ${index}. ${fix.title}`);
    out.push("");
    out.push(
      fix.kind === "FILE"
        ? `**File:** \`${fix.filePath}\`, served from \`${fix.targetUrl}\``
        : `**Page:** ${fix.targetUrl}`,
    );
    out.push("");

    if (fix.before) {
      out.push("**Currently:**");
      out.push("");
      out.push(fence(fix.before, "html"));
      out.push("");
    }
    if (fix.after) {
      out.push(fix.before ? "**Change to:**" : "**Add this:**");
      out.push("");
      out.push(fence(fix.after, fix.kind === "FILE" ? "" : "html"));
      out.push("");
    }
    out.push(fix.guidance);
    out.push("");
  }

  // Full file bodies, so the pack stands alone without the separate downloads.
  if (audit.robotsTxt || audit.sitemapXml) {
    out.push("## Appendix, generated files");
    out.push("");
    if (audit.robotsTxt) {
      out.push("### robots.txt");
      out.push("");
      out.push(fence(audit.robotsTxt));
      out.push("");
    }
    if (audit.sitemapXml) {
      out.push("### sitemap.xml");
      out.push("");
      out.push(fence(audit.sitemapXml, "xml"));
      out.push("");
    }
  }

  out.push("---");
  out.push("");
  out.push(
    "Search engines take days to weeks to reflect changes. GODEYE notifies the ones " +
      "that accept instant submissions (Bing, Yandex, Seznam, Naver) via IndexNow as " +
      "soon as a fix is verified. Google operates no equivalent, there the sitemap " +
      "is the route, and patience is the rest of it.",
  );
  out.push("");
  return out.join("\n");
}
